name: sat2sound
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pillow
  - h5py
  - pyyaml
  - tqdm
  - python-dateutil
  - pip:
      - pytorch-lightning==2.2.*
      - transformers==4.46.*
      - accelerate
      - datasets>=3.6,<4.0
      - huggingface-hub>=0.23.2,<1.0
      - pyarrow>=19.0
      - einops
      - timm
      - librosa
      - torchlibrosa
      - ruamel.yaml
      - yacs
      - gradio==4.44.*
      - folium==0.17.*
      - wandb
